<a href="https://colab.research.google.com/github/sowmi1407/Deep_recall1/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


##Introduction to tensors

###Creating tensors

In [ ]:
#scalars
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix=torch.tensor([[1,2],
                    [5,6]])
matrix

tensor([[1, 2],
        [5, 6]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#tensor
tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
tensor[0][2][1]

tensor(8)

###Random Tensors

In [ ]:
#creating a random tensor
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9775, 0.4873, 0.4720, 0.6009],
        [0.1507, 0.6777, 0.9510, 0.7959],
        [0.5736, 0.6402, 0.4228, 0.5127]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor=torch.rand(1,3,5)
random_tensor

tensor([[[0.4179, 0.2373, 0.6631, 0.2113, 0.9417],
         [0.5757, 0.0849, 0.2192, 0.8693, 0.8856],
         [0.3176, 0.1118, 0.9652, 0.2562, 0.3009]]])

In [ ]:
random_tensor.ndim,random_tensor.shape

(3, torch.Size([1, 3, 5]))

In [ ]:
zero=torch.zeros(1,2,3)
zero

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
ones=torch.ones(5,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#creating a tensor with range
range_tensor=torch.arange(start=0,end=1000,step=15)
range_tensor

tensor([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180, 195,
        210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360, 375, 390, 405,
        420, 435, 450, 465, 480, 495, 510, 525, 540, 555, 570, 585, 600, 615,
        630, 645, 660, 675, 690, 705, 720, 735, 750, 765, 780, 795, 810, 825,
        840, 855, 870, 885, 900, 915, 930, 945, 960, 975, 990])

In [ ]:
#to create tensors with similar shape to another tensor
zeros_like=torch.zeros_like(input=range_tensor)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

In [ ]:
float_16_tensor=torch.tensor([[9,8,7],
                              [6,7,8]],
                             dtype=torch.float16)
float_16_tensor

tensor([[9., 8., 7.],
        [6., 7., 8.]], dtype=torch.float16)

In [ ]:
torch.tensor([1,2,3],
             dtype=None, #to edit the datatype of the tensor
             device=None, #what device the tensor is on
             requires_grad=False) #whether or not to track the gradients

tensor([1, 2, 3])

In [ ]:
float_64_tensor=float_16_tensor.type(torch.float64)
float_64_tensor

tensor([[9., 8., 7.],
        [6., 7., 8.]], dtype=torch.float64)

In [ ]:
float_16_tensor*float_64_tensor

tensor([[81., 64., 49.],
        [36., 49., 64.]], dtype=torch.float64)

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_16_tensor*int_32_tensor

tensor([[27., 48., 63.],
        [18., 42., 72.]], dtype=torch.float16)

###Getting attributes from tensor

1. Getting datatype- use tensor.dtype
2. Getting shape   - use tensor.shape
3. Getting device  - use tensor.device

In [ ]:
tensor_random=torch.rand(3,4,5)
tensor_random

tensor([[[0.8790, 0.8717, 0.8518, 0.7690, 0.3915],
         [0.1343, 0.4252, 0.6183, 0.7524, 0.5414],
         [0.8814, 0.6363, 0.9865, 0.5614, 0.6668],
         [0.9933, 0.0162, 0.3951, 0.5109, 0.5043]],

        [[0.4543, 0.9183, 0.7739, 0.4709, 0.5554],
         [0.5021, 0.4498, 0.0794, 0.9025, 0.5810],
         [0.8932, 0.9147, 0.3382, 0.6913, 0.3368],
         [0.0536, 0.1075, 0.4883, 0.1019, 0.1291]],

        [[0.5960, 0.9203, 0.9636, 0.4073, 0.1418],
         [0.3173, 0.6567, 0.0509, 0.6981, 0.9970],
         [0.2781, 0.8462, 0.5318, 0.9749, 0.0116],
         [0.5799, 0.4332, 0.6460, 0.6977, 0.0210]]])

In [ ]:
tensor_random.shape,tensor_random.dtype,tensor_random.device

(torch.Size([3, 4, 5]), torch.float32, device(type='cpu'))

In [ ]:
int_32_tensor.shape,int_32_tensor.dtype,int_32_tensor.device

(torch.Size([3]), torch.int32, device(type='cpu'))

###Tensor Operations

1. Addition
2. Subtraction
3. Multiplication
4. division
5. Matrix Multiplication

In [ ]:
#addition
tensor_random+10

tensor([[[10.8790, 10.8717, 10.8518, 10.7690, 10.3915],
         [10.1343, 10.4252, 10.6183, 10.7524, 10.5414],
         [10.8814, 10.6363, 10.9865, 10.5614, 10.6668],
         [10.9933, 10.0162, 10.3951, 10.5109, 10.5043]],

        [[10.4543, 10.9183, 10.7739, 10.4709, 10.5554],
         [10.5021, 10.4498, 10.0794, 10.9025, 10.5810],
         [10.8932, 10.9147, 10.3382, 10.6913, 10.3368],
         [10.0536, 10.1075, 10.4883, 10.1019, 10.1291]],

        [[10.5960, 10.9203, 10.9636, 10.4073, 10.1418],
         [10.3173, 10.6567, 10.0510, 10.6981, 10.9970],
         [10.2781, 10.8462, 10.5318, 10.9749, 10.0116],
         [10.5799, 10.4332, 10.6460, 10.6977, 10.0210]]])

In [ ]:
#multiplication
tensor_random*21

tensor([[[18.4597, 18.3050, 17.8874, 16.1483,  8.2217],
         [ 2.8211,  8.9301, 12.9833, 15.8000, 11.3687],
         [18.5104, 13.3633, 20.7158, 11.7893, 14.0032],
         [20.8601,  0.3401,  8.2975, 10.7286, 10.5898]],

        [[ 9.5395, 19.2847, 16.2525,  9.8886, 11.6638],
         [10.5438,  9.4465,  1.6673, 18.9533, 12.2016],
         [18.7581, 19.2081,  7.1019, 14.5168,  7.0738],
         [ 1.1264,  2.2569, 10.2543,  2.1402,  2.7107]],

        [[12.5153, 19.3255, 20.2349,  8.5539,  2.9785],
         [ 6.6637, 13.7915,  1.0699, 14.6601, 20.9378],
         [ 5.8407, 17.7694, 11.1688, 20.4734,  0.2440],
         [12.1778,  9.0969, 13.5659, 14.6516,  0.4412]]])

In [ ]:
#subtraction
tensor_random-9

tensor([[[-8.1210, -8.1283, -8.1482, -8.2310, -8.6085],
         [-8.8657, -8.5748, -8.3817, -8.2476, -8.4586],
         [-8.1186, -8.3637, -8.0135, -8.4386, -8.3332],
         [-8.0067, -8.9838, -8.6049, -8.4891, -8.4957]],

        [[-8.5457, -8.0817, -8.2261, -8.5291, -8.4446],
         [-8.4979, -8.5502, -8.9206, -8.0975, -8.4190],
         [-8.1068, -8.0853, -8.6618, -8.3087, -8.6632],
         [-8.9464, -8.8925, -8.5117, -8.8981, -8.8709]],

        [[-8.4040, -8.0797, -8.0364, -8.5927, -8.8582],
         [-8.6827, -8.3433, -8.9490, -8.3019, -8.0030],
         [-8.7219, -8.1538, -8.4682, -8.0251, -8.9884],
         [-8.4201, -8.5668, -8.3540, -8.3023, -8.9790]]])

In [ ]:
#functions
tensor=torch.mul(tensor_random,10)
print(f"Multiplying 10 : {tensor}")
tensor=torch.add(tensor_random,10)
print(f"Adding 10 : {tensor}")

Multiplying 10 : tensor([[[8.7904, 8.7167, 8.5178, 7.6897, 3.9151],
         [1.3434, 4.2524, 6.1825, 7.5238, 5.4137],
         [8.8145, 6.3635, 9.8647, 5.6140, 6.6682],
         [9.9334, 0.1619, 3.9512, 5.1089, 5.0428]],

        [[4.5426, 9.1832, 7.7393, 4.7089, 5.5542],
         [5.0209, 4.4984, 0.7939, 9.0254, 5.8103],
         [8.9324, 9.1467, 3.3819, 6.9127, 3.3685],
         [0.5364, 1.0747, 4.8830, 1.0191, 1.2908]],

        [[5.9597, 9.2026, 9.6357, 4.0733, 1.4183],
         [3.1732, 6.5674, 0.5095, 6.9810, 9.9704],
         [2.7813, 8.4616, 5.3185, 9.7492, 0.1162],
         [5.7990, 4.3318, 6.4600, 6.9769, 0.2101]]])
Adding 10 : tensor([[[10.8790, 10.8717, 10.8518, 10.7690, 10.3915],
         [10.1343, 10.4252, 10.6183, 10.7524, 10.5414],
         [10.8814, 10.6363, 10.9865, 10.5614, 10.6668],
         [10.9933, 10.0162, 10.3951, 10.5109, 10.5043]],

        [[10.4543, 10.9183, 10.7739, 10.4709, 10.5554],
         [10.5021, 10.4498, 10.0794, 10.9025, 10.5810],
         [10.89

####Matrix Multiplication

1. Element wise multiplication
2. Multiplying with another matrix i.e dot product

In [ ]:
#Element wise multiplication
element_mul=int_32_tensor*float_16_tensor
element_mul

tensor([[27., 48., 63.],
        [18., 42., 72.]], dtype=torch.float16)

In [ ]:
#matrix multiplicationt
tensor_1=torch.rand(4,5)
tensor_2=torch.rand(5,4)

mat_mul=torch.matmul(tensor_1,tensor_2)
mat_mul_short=torch.mm(tensor_1,tensor_2)#alias of matmul
mat_mul,mat_mul_short

(tensor([[0.8328, 0.7737, 0.7398, 1.0156],
         [1.2114, 0.9758, 1.6953, 2.1485],
         [0.4158, 0.7590, 1.3216, 1.3597],
         [0.8014, 0.5625, 0.8112, 1.3123]]),
 tensor([[0.8328, 0.7737, 0.7398, 1.0156],
         [1.2114, 0.9758, 1.6953, 2.1485],
         [0.4158, 0.7590, 1.3216, 1.3597],
         [0.8014, 0.5625, 0.8112, 1.3123]]))

In [ ]:
#the most common error in matrix multiplication : shape error
tensor_mul_1=torch.rand(3,4)
tensor_mul_2=torch.rand(2,3)

mat_mul_tensor=torch.matmul(tensor_mul_1,tensor_mul_2) #the inner dimensions must match
mat_mul_tensor

RuntimeError: ignored

In [ ]:
#using transpose
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
tensor_A.T,tensor_B.T

(tensor([[1, 3, 5],
         [2, 4, 6]]), tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [ ]:
tensor_C=torch.mm(tensor_A,tensor_B.T)
tensor_C

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###Tensor Aggregation
1. Mean
2. Max
3. Min
4. Sum

In [ ]:
x=torch.arange(0,100,5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [ ]:
#min
torch.min(x)

tensor(0)

In [ ]:
#max
torch.max(x)

tensor(95)

In [ ]:
#mean
torch.mean(x)

RuntimeError: ignored

torch.mean doesnt work with int types.

In [ ]:
torch.mean(x.type(torch.float32))

tensor(47.5000)

In [ ]:
#sum
torch.sum(x)

tensor(950)

###Positional min and max

In [ ]:
#positional minimum
x.argmin()

tensor(0)

In [ ]:
#positional maximum
x.argmax()

tensor(19)

In [ ]:
x[0],x[19]

(tensor(0), tensor(95))

###Reshaping,stacking,squeezing and unsqueezing tensors

* Reshaping- reshaping the input tensor to a different tensor
* View     - return a view of an input tensor of certain shape but keep memory as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze  - remove dimensions from tensor
* Unsqueeze- add dimension to a tensor
* Permute  - return a view of the input with the dimensions permuted in a certain way

In [ ]:
x=torch.arange(1.,50.,5)
x

tensor([ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46.])

In [ ]:
x.shape

torch.Size([10])

In [ ]:
#reshaping
x_reshaped=x.reshape(5,2) #reshape has to be compatible with original shape
x_reshaped

tensor([[ 1.,  6.],
        [11., 16.],
        [21., 26.],
        [31., 36.],
        [41., 46.]])

In [ ]:
#change the view
z=x.view(10,1)
z,z.shape

(tensor([[ 1.],
         [ 6.],
         [11.],
         [16.],
         [21.],
         [26.],
         [31.],
         [36.],
         [41.],
         [46.]]), torch.Size([10, 1]))

In [ ]:
#changing z changes x because a view share the original tensor's memory
z[7,:]=52
z,x

(tensor([[ 1.],
         [ 6.],
         [11.],
         [16.],
         [21.],
         [26.],
         [31.],
         [52.],
         [41.],
         [46.]]), tensor([ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.]))

In [ ]:
#stacking
x_stacked=torch.stack([x,x],dim=0)
x_stacked

tensor([[ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.],
        [ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.]])

In [ ]:
x_stacked=torch.stack([x,x],dim=1)
x_stacked

tensor([[ 1.,  1.],
        [ 6.,  6.],
        [11., 11.],
        [16., 16.],
        [21., 21.],
        [26., 26.],
        [31., 31.],
        [52., 52.],
        [41., 41.],
        [46., 46.]])

In [ ]:
#squeezing
x=torch.arange(0.,10.)
x_reshaped=x.reshape(1,10)

x_squeezed=torch.squeeze(x_reshaped,dim=0)

In [ ]:
x_reshaped.shape,x_squeezed.shape

(torch.Size([1, 10]), torch.Size([10]))

In [ ]:
#unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
#permuting-returns a view with dimensions rearranged
x=torch.ones(size=(4,2,7))
x


tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
x_permuted=x.permute(2,0,1) #shifts axis 0->2, 1->0, 2->1


In [ ]:
x_permuted.shape,x.shape

(torch.Size([7, 4, 2]), torch.Size([4, 2, 7]))

###Indexing in PyTorch

In [ ]:
x=torch.arange(1.,10.).reshape(1,3,3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [ ]:
#indexing on the tensor
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x[0][0],x[0,0]

(tensor([1., 2., 3.]), tensor([1., 2., 3.]))

In [ ]:
x[0,1,1]

tensor(5.)

In [ ]:
x[0,2,1]

tensor(8.)

In [ ]:
#using : to select all values of a particular dimension
x[:,2]

tensor([[7., 8., 9.]])

In [ ]:
x[:,2,:]

tensor([[7., 8., 9.]])

In [ ]:
x[0,:,:]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

##PyTorch and NumPy

PyTorch has functionality to interact with NumPy

* Data in NumPy to PyTorch tensor `torch.from_numpy(ndarray)`
* Data in PyTorch tensor to NumPy `torch.Tensor.numpy(ndaray)`

In [ ]:
import torch
import numpy as np

array=np.arange(1.,8.)
tensor=torch.from_numpy(array)
tensor,array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

When converting from numpy to pytorch it reflects the datatype of numpy which is float64 whereas as the default datatype of torch is float32

In [ ]:
tensor=torch.ones(size=(3,3))
numpy_tensor=tensor.numpy()

In [ ]:
tensor,numpy_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]), array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32))

##Reproducability
To reduce randomness we use **random seed**.

In [ ]:
#creating 2 random tensors
random_tensor_A=torch.rand(4,5)
random_tensor_B=torch.rand(4,5)
random_tensor_A,random_tensor_B

(tensor([[0.8213, 0.3481, 0.5251, 0.6106, 0.6157],
         [0.4512, 0.0064, 0.2405, 0.1596, 0.7096],
         [0.2350, 0.9627, 0.8093, 0.9273, 0.7258],
         [0.2840, 0.3479, 0.9645, 0.4736, 0.1602]]),
 tensor([[0.7885, 0.1252, 0.5442, 0.9519, 0.1205],
         [0.6969, 0.6968, 0.8506, 0.9335, 0.5542],
         [0.3524, 0.3896, 0.1593, 0.5996, 0.0899],
         [0.7154, 0.9492, 0.8836, 0.9144, 0.4091]]))

In [ ]:
print(random_tensor_A==random_tensor_B)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [ ]:
#setting a random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_tensor_C=torch.rand(4,5)

torch.manual_seed(42)
random_tensor_D=torch.rand(4,5)

print(random_tensor_C==random_tensor_D)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


Use `torch.manal_seed()` every time you use a torch function because it works for only one instance of torch

##Running tensors and PyTorch objects on the GPU's


###Getting a GPU

1. Use the google colab gpu's
2. Use your own GPU
3. Use cloud computing- GCP,AWS and AZURE

For 2,3 PyTorch+CUDA will need some setting up

In [ ]:
##Checking for GPU
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
device='cuda' if torch.cuda.is_available() else 'cpu' #if gpu is available set device to cuda or else make it cpu
device

'cuda'

In [ ]:
torch.cuda.device_count() #counting the number of gpu's

1

###Putting Tensors to GPU's

In [ ]:
#creating a tensor
tensor=torch.rand([4,5],device='cpu')
print(tensor,tensor.device)




tensor([[0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423]]) cpu


In [ ]:
#move tensor to gpu
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([[0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423]], device='cuda:0')

In [ ]:
#if tensor is on gpu we cant convert it to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
#to fix the above thing
tensor_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([[0.26963168, 0.44136357, 0.29692084, 0.8316855 , 0.10531491],
       [0.26949483, 0.35881263, 0.19936377, 0.54719156, 0.00616044],
       [0.95155454, 0.07526588, 0.8860137 , 0.5832096 , 0.33764774],
       [0.808975  , 0.5779254 , 0.9039817 , 0.55465984, 0.3423134 ]],
      dtype=float32)